Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code

to print the data types of both the variables.

#Answer

Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, and

array_list is a NumPy array. we can use the type() function to print the data types of both variables


In [15]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


As you can see, the data type of list_ is list, and the data type of array_list is numpy.ndarray.

                      -------------------------------------------------------------------

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [ ]:
#Answer

import numpy as np
list_ = [ '1', '2', '3', '4', '5']
array_list = np.array(object=list_)

#print the data types of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))
    
#print the data types of each element in array_list
print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

                      -------------------------------------------------------------------

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and

arra_list? If so then print the data types of each and every element present in both the variables, list_

and array_list.


#Answer

Yes, there will be a difference in the data type of the elements between list_ and array_list due to the specified dtype=int

when creating the NumPy array. Here's the modified code to print the data types of each element in both variables:

In [22]:


import numpy as np
list_ = [ '1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype = int)

#print the data types of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))
    
#print the data types of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As you can see, after specifying dtype=int when creating array_list, the elements in array_list are of type numpy.int64, while the elements in list_ remain of type str.

                      -------------------------------------------------------------------

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [43]:
#Answer

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#print the shape and size of variable num_array:
print("Shape of varaible num_array is:", num_array.shape)

#print the shape and size of variable num_array:
print("\nSize of varaible num_array is:", num_array.size)



Shape of varaible num_array is: (2, 3)

Size of varaible num_array is: 6


                      -------------------------------------------------------------------

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [62]:
#Answer

import numpy as np

# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the result
print("3x3 Matrix of Zeros:")
print(zero_matrix)



3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


                       -------------------------------------------------------------------

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [68]:
#Answer

import numpy as np

identity_matrix = np.eye(5, 5)

#print result
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


                        -------------------------------------------------------------------